[package]
name = "images-to-h264"
version = "0.1.0"
authors = ["nintha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
image = "0.23.12"
x264 = { path = "./crate_x264" }
clap = "3.0.0-beta.2"